services:
  backend:
    image: minifrizz/diving-o-club-backend:latest
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    image: minifrizz/diving-o-club-frontend:latest
    ports:
      - "80:3000"
    environment:
      DB_ENABLED: "false"
    depends_on:
      - backend
    restart: unless-stopped
