name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend image
        run: |
          docker build -t minifrizz/diving-o-club-backend:latest ./app/backend
          docker push minifrizz/diving-o-club-backend:latest
      
      - name: Build and push frontend image
        run: |
          docker build -t minifrizz/diving-o-club-frontend:latest ./app/frontend
          docker push minifrizz/diving-o-club-frontend:latest
      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Diving-O-Club_App
            echo "ğŸ§¹ Cleaning old Docker data..."
            sudo docker image prune -af
            echo "â†ªï¸ Pulling latest changes..."
            git fetch origin main
            git reset --hard origin/main
            echo "ğŸ† Pulling images..."
            sudo docker compose pull
            echo "ğŸ”„ Restarting containers..."
            sudo docker compose up -d
            echo "ğŸ”„ Restarting Nginx..."
            sudo systemctl restart nginx
            echo "ğŸŸ¢ Deployed successfully!"
            sudo docker compose ps